# CMake generated Testfile for 
# Source directory: E:/Source/gtest/googletest
# Build directory: E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gtest-death-test_test "gtest-death-test_test")
add_test(gtest_environment_test "gtest_environment_test")
add_test(gtest-filepath_test "gtest-filepath_test")
add_test(gtest-linked_ptr_test "gtest-linked_ptr_test")
add_test(gtest-listener_test "gtest-listener_test")
add_test(gtest_main_unittest "gtest_main_unittest")
add_test(gtest-message_test "gtest-message_test")
add_test(gtest_no_test_unittest "gtest_no_test_unittest")
add_test(gtest-options_test "gtest-options_test")
add_test(gtest-param-test_test "gtest-param-test_test")
add_test(gtest-port_test "gtest-port_test")
add_test(gtest_pred_impl_unittest "gtest_pred_impl_unittest")
add_test(gtest_premature_exit_test "gtest_premature_exit_test")
add_test(gtest-printers_test "gtest-printers_test")
add_test(gtest_prod_test "gtest_prod_test")
add_test(gtest_repeat_test "gtest_repeat_test")
add_test(gtest_sole_header_test "gtest_sole_header_test")
add_test(gtest_stress_test "gtest_stress_test")
add_test(gtest-test-part_test "gtest-test-part_test")
add_test(gtest_throw_on_failure_ex_test "gtest_throw_on_failure_ex_test")
add_test(gtest-typed-test_test "gtest-typed-test_test")
add_test(gtest_unittest "gtest_unittest")
add_test(gtest-unittest-api_test "gtest-unittest-api_test")
add_test(gtest-death-test_ex_nocatch_test "gtest-death-test_ex_nocatch_test")
add_test(gtest-death-test_ex_catch_test "gtest-death-test_ex_catch_test")
add_test(gtest_no_rtti_unittest "gtest_no_rtti_unittest")
add_test(gtest_break_on_failure_unittest "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_break_on_failure_unittest.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_catch_exceptions_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_catch_exceptions_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_color_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_color_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_env_var_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_env_var_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_filter_unittest "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_filter_unittest.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_help_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_help_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_list_tests_unittest "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_list_tests_unittest.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_output_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_output_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_shuffle_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_shuffle_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_throw_on_failure_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_throw_on_failure_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_uninitialized_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_uninitialized_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_xml_outfiles_test "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_xml_outfiles_test.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
add_test(gtest_xml_output_unittest "F:/Green/Language/Python/3.5/x64/python.exe" "E:/Source/gtest/googletest/test/gtest_xml_output_unittest.py" "--build_dir=E:/Working/dbyoung/VS2015/Source/13.gtest/googlemock/gtest/${CTEST_CONFIGURATION_TYPE}")
